=== lukaslussi/M242/Avr/ToolChain/xml/EntityDescription.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="EntityDescription" 
           targetNamespace="http://tempuri.org/EntityDescription.xsd" 
           elementFormDefault="qualified" 
           xmlns="http://tempuri.org/EntityDescription.xsd" 
           xmlns:mstns="http://tempuri.org/EntityDescription.xsd" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="SupportedChipFamilies">
    <xs:restriction>
      <xs:simpleType>
        <xs:list itemType="xs:NCName"/>
      </xs:simpleType>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="HexInt">
    <xs:restriction base="xs:token">
      <xs:pattern value="(0x)?[0-9a-fA-F]+" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ProcessingUnitType">
    <xs:sequence>
      <xs:element name="Import" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="LibraryOrFile" type="xs:string" use="required"></xs:attribute>
          <xs:attribute name="ByReference" type="xs:boolean" use="required"></xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element name="TypeDefinition" type="TypeDescriptionType" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:element name="MemorySection" type="MemorySectionT" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Namespace" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="TypeDescriptionType">
    <xs:sequence>
      <xs:element name="Description" type="xs:string" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:ID" use="required" />
  </xs:complexType>
  <xs:simpleType name="AccessType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ReadOnly" />
      <xs:enumeration value="WriteOnly"  />
      <xs:enumeration value="ReadWrite" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="FieldDescriptionType">
    <xs:sequence>
      <xs:element name="Description" type="xs:string" minOccurs="0" />
      <xs:element name="Position" type="xs:integer" minOccurs="0" maxOccurs="1" />
      <xs:element name="Access" type="AccessType" minOccurs="0" />
      <xs:element name="Skip" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            This field is used to mark fields as not accessible by debuggers; This is the case for any fifo register. 
            Accessing this fields will interfere with the operaton of the application. Skip defaults to "false"
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="FieldType" type="xs:string" use="required"/>
    <xs:attribute name="Aligned" type="xs:integer" use="optional"/>
  </xs:complexType>
  <xs:complexType name="StructType">
    <xs:complexContent>
      <xs:extension base="TypeDescriptionType">
        <xs:sequence>
          <xs:element name="TypeDefinition" type="TypeDescriptionType" minOccurs="0" maxOccurs="unbounded" />
          <xs:element name="Field" type="FieldDescriptionType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="IntegerType">
    <xs:complexContent>
      <xs:extension base="TypeDescriptionType">
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element name="Bitfield" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:all>
                <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Default" type="xs:integer" minOccurs="0" maxOccurs="1" />
                <xs:element name="Access" type="AccessType" minOccurs="0" maxOccurs="1">
                  <xs:annotation>
                    <xs:documentation>
                      Access defaults to ReadWrite
                    </xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element name="ValueSet" type="EnumType" minOccurs="0"/>
              </xs:all>
              <xs:attribute name="Name" type="xs:string" use="required" />
              <xs:attribute name="Width" type="xs:integer" use="required" />
              <xs:attribute name="Position" type="xs:integer" use="required"/>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="Size" type="xs:integer" use="required">
          <xs:annotation>
            <xs:documentation>
              Specifies the number of bytes of this integer type
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="Signed" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EnumType">
    <xs:complexContent>
      <xs:extension base="TypeDescriptionType">
        <xs:sequence>
          <xs:element name="Enum" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
              <xs:attribute name="Name" use="required"/>
              <xs:attribute name="Value" type="HexInt" use ="optional"/>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="Size" type="xs:integer" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="MemorySymbolT">
    <xs:sequence>
      <xs:element name="Description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:NCName" use="required"/>
    <xs:attribute name="Offset" type="HexInt" use ="required"/>
    <xs:attribute name="Type" type="xs:NCName" use="required"/>
  </xs:complexType>
  <xs:complexType name="MemorySectionT">
    <xs:sequence>
      <xs:element name="Description" type="xs:string" maxOccurs="1" minOccurs="0"/>
      <xs:element name="Symbol" type="MemorySymbolT" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:NCName"></xs:attribute>
    <xs:attribute name="Address" type="HexInt"/>
    <xs:attribute name="ByteOrder" use="optional"/>
    <xs:attribute name="Chip" type="SupportedChipFamilies" use ="required"/>
  </xs:complexType>
  <xs:element name="Unit" type="ProcessingUnitType" />
</xs:schema>

=== lukaslussi/M242/Avr/ToolChain/xml/Atmega328P.xml
<?xml version="1.0" encoding="utf-8"?>
<Unit xmlns ="http://tempuri.org/EntityDescription.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:schemaLocation="http://tempuri.org/EntityDescription.xsd ../../Schema/EntityDescription.xsd"
      Name="IntTypes" Namespace="Types">
  <Import LibraryOrFile="../../Ctypes/IntTypes.xml" ByReference="true" />

  <TypeDefinition Name="SMCR_T" xsi:type="IntegerType" Signed="false" Size="1">
    <Description>Sleep mode control register</Description>
    <Stereotype>HardwareRegister</Stereotype>
    <Bitfield Name="SE" Position="0" Width="1">
      <Description>Sleep enable</Description>
    </Bitfield>
    <Bitfield Name="SM" Position="1" Width="3">
      <Description>Sleep mode</Description>
      <ValueSet Name="SleepMode">
        <Enum Name="Idle" Value="0"/>
        <Enum Name="AdcNoiseRed" Value="1"/>
        <Enum Name="PowerDown" Value="2"/>
        <Enum Name="PowerSave" Value="3"/>
        <Enum Name="StandBy" Value="6"/>
        <Enum Name="ExtStandBy" Value="7"/>
      </ValueSet>
    </Bitfield>
  </TypeDefinition>
  
  <TypeDefinition Name="MCUCR_T" xsi:type="IntegerType" Size="1" Signed="false">
    <Description>MCU control register</Description>
    <Stereotype>HardwareRegister</Stereotype>
    <Bitfield Name="IVCE" Position="0" Width="1"/>
    <Bitfield Name="IVSEL" Position="1" Width="1"/>
    <Bitfield Name="PUD" Position="4" Width="1">
      <Description>Pull up disable</Description>
    </Bitfield>
    <Bitfield Name="BODSE" Position="5" Width="1"></Bitfield>
    <Bitfield Name="BODS" Position="6" Width="1"></Bitfield>
  </TypeDefinition>
  

  <TypeDefinition Name ="GPIO_T" xsi:type="StructType">
    <Description>
    </Description>
    <Stereotype>HardwarePeripheral</Stereotype>
    <TypeDefinition Name="PIN_T" xsi:type="IntegerType" Size="1" Signed="false">
      <Description>Bitmaps for port pins</Description>
      <Bitfield Name="0" Width ="1" Position ="0">
        <Default>0</Default>
      </Bitfield>
      <Bitfield Name="_1" Width ="1" Position ="1">
        <Default>0</Default>
      </Bitfield>
      <Bitfield Name="_2" Width ="1" Position ="2">
        <Default>0</Default>
      </Bitfield>
      <Bitfield Name="_3" Width ="1" Position ="3">
        <Default>0</Default>
      </Bitfield>
      <Bitfield Name="_4" Width ="1" Position ="4">
        <Default>0</Default>
      </Bitfield>
      <Bitfield Name="_5" Width ="1" Position ="5">
        <Default>0</Default>
      </Bitfield>
      <Bitfield Name="_6" Width ="1" Position ="6">
        <Default>0</Default>
      </Bitfield>
      <Bitfield Name="_7" Width ="1" Position ="7">
        <Default>0</Default>
      </Bitfield>
    </TypeDefinition>
    <TypeDefinition Name="DataDirection_T" xsi:type="EnumType" Size="1">
      <Enum Name="DdrInput" Value="0"/>
      <Enum Name="DdrOutput" Value="1"/>
    </TypeDefinition>
    <Field Name="PIN" FieldType="PIN_T" Aligned="1">
      <Description>Port input data</Description>
    </Field>
    <Field Name="DDR" FieldType="PIN_T" Aligned="1">
      <Description>Data direction register</Description>
    </Field>
    <Field Name="PORT" FieldType="PIN_T" Aligned="1">
      <Description>Port data or pull up</Description>
    </Field>
  </TypeDefinition>
  
  <TypeDefinition Name="TCNT8_T" xsi:type="StructType">
    <Description>8 bit timer counter
    </Description>
    <Stereotype>HardwarePeripheral</Stereotype>
    <TypeDefinition Name="TCCRA_T" xsi:type="IntegerType" Size="1" Signed="false">
      <Bitfield Name="WGM" Position="0" Width="2">
        <Description>
        Waveform generation mode:
          0 = Normal
          1 = PWM, normal mode
          2 = CTC (clear timer on compare match)
          3 = Fast PWM
        </Description>
        <ValueSet Name ="WaveFormGenerationModes">
          <Enum Name ="Normal"  Value="0"/>
          <Enum Name ="PwmNormal" Value ="1"/>
          <Enum Name ="ClrTmrOnCmpMatch" Value ="2"/>
          <Enum Name ="FastPwm" Value ="3"/>
        </ValueSet>
      </Bitfield>
      <Bitfield Name="COMB" Position="4" Width="2">
        <Description>Compare output mode; depending on the setting in WGM COMB has a different meaning</Description>
      </Bitfield>
      <Bitfield Name="COMA" Position="6" Width="2">
        <Description>Defines behavior of OCA on a compare match</Description>
      </Bitfield>
    </TypeDefinition>
    <TypeDefinition Name="TCCRB_T" xsi:type="IntegerType" Signed="false" Size="1">
      <Bitfield Name="CS" Position="0" Width="3">
        <Description>
          Clock selection; The clock selection options are slightly different for counter 1 and counter 2; The enum ClkSelect defines the values for 
          both! The values that are applicable for both have the prefix CS_; the ones that are applicable only for one of them have the prefix 
          CsT1_, CsT2_ respectiviely.
        </Description>
        <ValueSet Name="ClkSelect">
          <Description> This enumerate defines both</Description>
          <Enum Name ="CS_Off" Value="0"/>
          <Enum Name ="CS_Div1" Value="1"/>
          <Enum Name ="CS_Div8" Value="2"/>
          <Enum Name ="CsT1_Div64" Value="3"/>
          <Enum Name ="CsT1_Div256" Value="4"/>
          <Enum Name ="CsT1_Div1024" Value="5"/>
          <Enum Name ="CsT1_T0Falling" Value="6"/>
          <Enum Name ="CsT1_T0Raising" Value="7"/>
          <Enum Name="CsT2_Div32" Value="3"/>
          <Enum Name="CsT2_Div64" Value="4"/>
          <Enum Name="CsT2_Div128" Value="5"/>
          <Enum Name="CsT2_Div256" Value="6"/>
          <Enum Name="CsT2_Div1024" Value="7"/>
        </ValueSet>
      </Bitfield>
      
      <Bitfield Name="WGM" Position="3" Width="1">
        <Description>Select PWM mode if set to 1</Description>
      </Bitfield>
      <Bitfield Name="Reserved" Position="4" Width="2"/>
      <Bitfield Name="FOCB" Position="6" Width="1">
        <Description>Force output compare on OCRB; takes effect if WGM bit not set to 1</Description>
      </Bitfield>
      <Bitfield Name="FOCA" Position="7" Width="1">
        <Description>Force output compare on OCRA; takes effect if WGM bit not set to 1</Description>
      </Bitfield>
    </TypeDefinition>
    <Field Name="TCCRA" FieldType="TCCRA_T" Aligned="1"></Field>
    <Field Name="TCCRB" FieldType="TCCRB_T" Aligned="1"></Field>
    <Field Name="TCNT" FieldType="uint8_t" Aligned="1"></Field>
    <Field Name="OCRA" FieldType="uint8_t" Aligned="1"></Field>
    <Field Name="OCRB" FieldType="uint8_t" Aligned="1"></Field>
  </TypeDefinition>


  <TypeDefinition Name="TCNT16_T" xsi:type="StructType">
    <Stereotype>HardwarePeripheral</Stereotype>
    <TypeDefinition Name="TCCRA1_T" xsi:type="IntegerType" Signed="false" Size="1">
      <Bitfield Name="WGM" Position="0" Width="2">
        <Description>Wave form generation mode; the value is combinde with the field WGM in TCCRB1_T. 
        The description how to usd the combinde value can be found in table 15-5 of the data sheet!
        </Description>
      </Bitfield>
      <Bitfield Name="COM1B" Position="4" Width="2"></Bitfield>
      <Bitfield Name="COM1A" Position="6" Width="2"></Bitfield>
    </TypeDefinition>
    <TypeDefinition Name="TCCRB1_T" xsi:type="IntegerType" Signed="true" Size="1">
      <Bitfield Name="CS" Position="0" Width="3">
        <Description>Clock selection; the same values as for CS in timer 0 are applicable!</Description>
      </Bitfield>
      <Bitfield Name="WGM" Position="4" Width="2">
        <Description>Upper bits of wave generation mode; is combined with WGM in TCCRA1 register</Description>
      </Bitfield>
      <Bitfield Name="ICES1" Position="6" Width="1">
        <Description>Input capture edge select; 
        * 1: capture on raising edge
        * 0: capture on falling edge
        </Description>
      </Bitfield>
      <Bitfield Name="ICNC1" Position="7" Width="1">
        <Description>Enable noise canceller on input capture</Description>
      </Bitfield>
    </TypeDefinition>
    <TypeDefinition Name="TCCRC1_T" xsi:type="IntegerType" Size="1" Signed="false">
      <Bitfield Name="FOC1B" Position="6" Width="1">
        <Description>Force compare match on channel B</Description>
      </Bitfield>
      <Bitfield Name="FOC1A" Position="7" Width="1">
        <Description>Force compare match on channel A</Description>
      </Bitfield>
    </TypeDefinition>
    <Field Name="TCCRA" FieldType="TCCRA1_T">
      <Description>Timer configuration register A</Description>
    </Field>
    <Field Name="TCCRB" FieldType="TCCRB1_T">
      
    </Field>
    <Field Name="TCCRC" FieldType ="TCCRC1_T">
      
    </Field>
    <Field Name="Reserved" FieldType="uint8_t"/>
    <Field Name="TCNT" FieldType="uint16_t">
      <Description>Counter register</Description>
    </Field>
    <Field Name="ICR" FieldType="uint16_t">
      <Description>Input capture register</Description>
    </Field>
    <Field Name="OCRA" FieldType="uint16_t">
      <Description>Output compare register A</Description>
    </Field>
    <Field Name="ORCB" FieldType="uint16_t">
      <Description>Output compare register B</Description>
    </Field>
  </TypeDefinition>

  
  <TypeDefinition Name="TIFR_T" xsi:type="IntegerType" Size="1" Signed="false">
    <Description>Timer interrupt flag register</Description>
    <Stereotype>HardwareRegister</Stereotype>
    <Bitfield Name="TOV" Position="0" Width="1">
      <Description>Timer overflow occurred</Description>
    </Bitfield>
    <Bitfield Name="OCFA" Position="1" Width="1">
      <Description>Timer output compare match occured with register OCRA</Description>
    </Bitfield>
    <Bitfield Name="OCFB" Position="2" Width="1">
      <Description>Timer output compare match occured register OCRB</Description>
    </Bitfield>
    <Bitfield Name="ICF" Position="5" Width="1">
      <Description>Input capture flag</Description>
    </Bitfield>
  </TypeDefinition>
